# Starknet Foundry configuration

[sncast.guessnft_deployer]
account = "guessnft_deployer"
accounts-file = "~/.starknet_accounts/starknet_open_zeppelin_accounts.json"
network = "sepolia"

[sncast.mainnet]
account = "native_mainnet"
url = "https://api.cartridge.gg/x/starknet/mainnet"

